#34 - Explicitly defined base branch
XavierGuertin/WildfireVisualizationProject pull request #55
Opened 2024-10-28 03:58 UTC by LiamDaigle

We are not using "main" as our main branch. Instead we are using "dev". Since we never stated this in the .yml file, the CI was defaulting to looking for a "main" branch.

2024-10-28 04:18 UTC, yasminehilout approved these changes
Well done!

2024-10-31 14:30 UTC, XavierGuertin approved these changes

2024-10-31 14:31 UTC, XavierGuertin requested changes
Please refer to the [Naming Convention](https://github.com/XavierGuertin/WildfireVisualizationProject/wiki/Name-Conventions) for the title of the PR

2024-11-02 18:06 UTC, XavierGuertin approved these changes

2024-11-02 19:05 UTC, merged