#48 - feat(frontend):  Added Sidebar for Available Datasets
XavierGuertin/WildfireVisualizationProject pull request #67
Opened 2024-11-04 08:04 UTC by yasminehilout

## **#48 - feat(AvailableDatasets): Enhance dataset selection and collapse functionality**

---

### **Summary**
This PR introduces several improvements to the `AvailableDatasets` component, including a user-friendly collapse functionality, visual enhancements for dataset selection, and modular component refactoring to streamline the `Layout` structure. The changes aim to improve user experience by simplifying access to relevant datasets based on the map region.

### **Changes Made**
- **Component Enhancements:**
  - Added a collapse button for the `AvailableDatasets` sidebar, allowing users to toggle its visibility.
  - Highlighted the selected dataset with a distinct background color for better visual feedback.
  - Removed the draggable effect on the sidebar for a fixed position.
  - Updated the Metadata Component with selected Database

- **Refactoring:**
  - Created independent `Layers` and `AvailableDatasets` components to improve code modularity.
  - Updated `Layout` to directly integrate `Layers` and `AvailableDatasets`.

- **Styling and UI:**
  - Updated the `AvailableDatasets` UI for a cohesive look, aligning with the overall theme.

### **Testing Instructions**
To test these changes, run the following:
`nx serve frontend`

**Verify that:**

- The AvailableDatasets component can collapse and expand using the new button.
- The selected dataset's background color changes to indicate selection.
- The Layers and AvailableDatasets components load directly in Layout without issues.
- The Metadata Component is updated when a different dataset is selected
- The filters for the datasets do in fact filter the datasets correctly.

![Update_222](https://github.com/user-attachments/assets/9d21cb57-be6f-49ff-af1e-1bf9d656ba75)

https://github.com/user-attachments/assets/02419d75-5ff6-44a3-be9f-26ffac8677ab

2024-11-06 14:16 UTC, XavierGuertin requested changes

2024-11-06 14:16 UTC, XavierGuertin commented on apps/frontend/src/app/components/AvailableDatasets.tsx
> +            <svg width="39" height="38" viewBox="0 0 39 38" fill="none" xmlns="http://www.w3.org/2000/svg">
why not use an icon instead?

2024-11-06 14:16 UTC, XavierGuertin commented on apps/frontend/src/app/components/AvailableDatasets.tsx
> +            <path d="M42 10C42 13.3137 33.9411 16 24 16C14.0589 16 6 13.3137 6 10M42 10C42 6.68629 33.9411 4 24 4C14.0589 4 6 6.68629 6 10M42 10V38C42 41.32 34 44 24 44C14 44 6 41.32 6 38V10M42 24C42
same here

2024-11-06 14:16 UTC, XavierGuertin commented on apps/frontend/src/app/components/AvailableDatasets.tsx
> +            <svg width="39" height="38" viewBox="0 0 39 38" fill="none" xmlns="http://www.w3.org/2000/svg">
same here

2024-11-06 14:16 UTC, XavierGuertin commented on apps/frontend/src/app/layout.tsx
> +interface Dataset {
I don't think this is the right place to define an interface. This class should stricly be about the layout of the main page

2024-11-06 21:38 UTC, yasminehilout commented on apps/frontend/src/app/components/AvailableDatasets.tsx
> +            <svg width="39" height="38" viewBox="0 0 39 38" fill="none" xmlns="http://www.w3.org/2000/svg">
Because it was easier to just copy the svg format from Figma.

2024-11-07 00:21 UTC, yasminehilout commented on apps/frontend/src/app/layout.tsx
> +interface Dataset {
fixed

2024-11-07 00:25 UTC, im-samwong approved these changes
LGTM

2024-11-07 00:25 UTC, lo-vil approved these changes
looks good to sam

2024-11-07 01:53 UTC, XavierGuertin approved these changes

2024-11-07 01:55 UTC, merged